[project]
name = "resolveiq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "groq>=1.7.0",
    "ipykernel>=7.3.0",
    "ipython>=9.17.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]
